name: CI Pipeline
run-name: "CI pipeline is running"

on:  
  push: 

jobs:
  build-and-validate:
    name: Build & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "This is my first pipeline"

      - name: Info
        run: echo "this is my second step"
   
  
