name: "Salesforce Pipeline"
run-name: "Salesforce Pipeline Run"

on:
  pull_request:
    paths:
      - 'force-app/**'
    branches:
      - abc_feature/**

env:
  ORG_DEFAULT_ALIAS: PROD_ORG
  NODE_VERSION: ">=20.9.0"
  JAVA_VERSION: ">=11"
  SF_CLI_VERSION: latest
  ORG_VARIABLE: ${{ vars.ORGANIZATION_VARIABLE }}

permissions:
  contents: read
  pull-requests: write
  actions: read
  
jobs:
    build-salesforce: 
      name: "Build & Validate"
      uses: "./.github/workflows/template.yaml"
      with:
        envionment: dev
        runner: macos-latest
      secrets: inherit
      #secrets: 
      #  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        