name: "Salesforce Deployment POC"
run-name: "Salesforce Deployment POC"
on:
  push:

jobs:
  setup-and-deploy:
    name: "Setup and Deploy to Salesforce Org"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout Repository"
        uses: actions/checkout@v7.0.1

      - name: "Setup salesforce cli"
        run: npm install --global @salesforce/cli@latest

      - name: "check sf version"
        run: sf --version

      - name: "Install Salesforce Code Analytics Plugin"
        run: echo 'y'| sf plugins:install code-analyzer

      - name: Authenticate to Salesforce Org
        run: |
          
          sf org login sfdx-url --sfdx-url-file authFile.json --set-default --alias dev1 

      - name: "Deploy to Salesforce Org"
        run: sf project deploy start --source-dir force-appmain/default --target-org dev1

      - name: "Assign permission set to user"
        run: sf org assign permset assign --name Onboarding_Manager --on-behalf-of varunb195@gmail.com.dev --target-org dev1
           

      