name: "Salesforce Deployment POC"
run-name: "Salesforce Deployment POC"
on:
  push:

jobs:
  setup-and-deploy:
    name: "Setup and Deploy to Salesforce Org"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout Repository"
        uses: actions/checkout@v7.0.1

      # PREREQUISITES - Only needed if the runner doesn't already satisfy these requirements.
      - name: Ensure node v20.9.0 or greater
        uses: actions/setup-node@v5
        with:
          node-version: '>=20.9.0'
      - name: Ensure java v11 or greater
        uses: actions/setup-java@v5
        with:
          java-version: '>=11'
          distribution: 'zulu'
      - name: Ensure python v3.10 or greater
        uses: actions/setup-python@v6
        with:
          python-version: '>=3.10'

      - name: "Setup salesforce cli"
        run: npm install --global @salesforce/cli@latest

      - name: "check sf version"
        run: sf --version

      - name: "Install Salesforce Code Analytics Plugin"
        run: echo 'y'| sf plugins install code-analyzer@latest

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v2
        with:
          run-arguments: --workspace . --view detail --output-file sfca_results.html --output-file sfca_results.json
          results-artifact-name: salesforce-code-analyzer-results
          github-token: ${{ github.token }}

      - name: Authenticate to Salesforce Org
        run: |
          
          sf org login sfdx-url --sfdx-url-file authFile.json --set-default --alias dev1 

      - name: "Deploy to Salesforce Org"
        run: sf project deploy start --source-dir force-app/main/default --target-org dev1 --ignore-conflicts

      - name: "Assign permission set to user"
        run: sf org assign permset  --name Onboarding_Manager --on-behalf-of varunb195@gmail.com.dev --target-org dev1
           

      